validator:
  basic: yes
save_pipeline: yes
channels:
- number: 13
  sample_rate: 2000
  type: LFP
- number: 14
  sample_rate: 2000
  type: LFP
- number: 15
  sample_rate: 2000
  type: LFP
- number: 16
  sample_rate: 2000
  type: LFP
- number: 24
  sample_rate: 2000
  type: LFP
subject_code: YAB
project_name: demo
file_format: 1.0
blocks:
- 008
- '010'
- '011'
- '012'
physical_unit: as-is
